// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD0lm3W4gkpEardmd28v31V1M3cPhVTks',
    appId: '1:256460604983:web:971e4014cd43dfe3c6a1b2',
    messagingSenderId: '256460604983',
    projectId: 't2-dsm-952e7',
    authDomain: 't2-dsm-952e7.firebaseapp.com',
    storageBucket: 't2-dsm-952e7.appspot.com',
    measurementId: 'G-RN6VTB9K0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDygEfohD_Y3xEXa3VIYnTzvENDjvb2Afs',
    appId: '1:256460604983:android:d8547b8b9c9b9586c6a1b2',
    messagingSenderId: '256460604983',
    projectId: 't2-dsm-952e7',
    storageBucket: 't2-dsm-952e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3UUH1H5YnXKtMGa3DwEMX-lwWMruK9qY',
    appId: '1:256460604983:ios:893ca7a7c2630b18c6a1b2',
    messagingSenderId: '256460604983',
    projectId: 't2-dsm-952e7',
    storageBucket: 't2-dsm-952e7.appspot.com',
    iosClientId: '256460604983-enm785p1bb56c267g9ai5dfb48fhg4lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.t2Dsw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3UUH1H5YnXKtMGa3DwEMX-lwWMruK9qY',
    appId: '1:256460604983:ios:893ca7a7c2630b18c6a1b2',
    messagingSenderId: '256460604983',
    projectId: 't2-dsm-952e7',
    storageBucket: 't2-dsm-952e7.appspot.com',
    iosClientId: '256460604983-enm785p1bb56c267g9ai5dfb48fhg4lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.t2Dsw',
  );
}
